volumes:
  my-db:

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  keycloak:
    depends_on:
      mysql:
        condition: service_healthy
    image: quay.io/keycloak/keycloak:22.0.3
    environment:
      DB: MYSQL
      DB_URL_HOST: mysql
      DB_SCHEMA: keycloak
      DB_USERNAME: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_PROXY: edge
    ports:
      - 8080:8080
      - 8443:8443
    command:
      - start