volumes:
  my-db:

services:
  mysql:
    image: mysql:8.4.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      default-authentication-plugin: caching_sha2_password
      TZ: Asia/Bangkok
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: "mysql"
      KC_DB_URL: 'jdbc:mysql://mysql:3306/keycloak'
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTPS_KEY_STORE_PASSWORD: secret
      KC_PROXY: edge
      ENV KC_HTTP_ENABLED: true 
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    command: ["start"]
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy