
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jswiki
  namespace: jswiki
spec:
  ingressClassName: nginx
  rules:
  - host: jswiki.tanat44.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: jswiki
            port:
              number: 80
