apiVersion: v1
kind: PersistentVolume
metadata:
  name: vanilla-pv
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/vanilla-volume"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vanilla-pvc
spec:
  volumeName: vanilla-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi