
apiVersion: v1
kind: Service
metadata:
  name: vanilla-init-service
spec:
  selector:
    app: vanilla-init-container
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vanilla-init-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: vanilla
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vanilla-init-service
            port:
              number: 80