- name: My first play
  hosts: myhosts
  tasks:
    - name: print message
      ansible.builtin.debug:
        msg: Hello world

    - name: creating with admin access
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        groups: sudo 
        state: present
        shell: /bin/bash

    - name: Add authorized key
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"