- name: install k3s node
  hosts: 
    - tanut2
    - tanut3

  tasks:
    - name: install k3s
      shell: |
        sudo curl -Lo /usr/local/bin/k3s https://github.com/k3s-io/k3s/releases/download/v1.33.3%2Bk3s1/k3s
        sudo chmod +x /usr/local/bin/k3s
        curl -Lo install.sh https://get.k3s.io
        chmod +x install.sh
        INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://{{ controlplane_ip }}:6443 K3S_TOKEN={{ controlplane_token }} ./install.sh
      become: true

    - name: stop k3s
      shell: |
        sudo systemctl stop k3s
      become: true

    - copy:
        src: "{{ item }}"
        dest: /etc/rancher/k3s/
        owner: root
        mode: 644
      become: true
      with_fileglob:
        - "../asset/*"

    - name: start k3s
      shell: |
        sudo systemctl stop k3s
      become: true