- name: download k3s
  shell: |
    sudo curl -Lo /usr/local/bin/k3s https://github.com/k3s-io/k3s/releases/download/v1.33.3%2Bk3s1/k3s
    sudo chmod +x /usr/local/bin/k3s
    curl -Lo install.sh https://get.k3s.io
    chmod +x install.sh
  become: true