---
# Source: eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  labels:
    helm.sh/chart: eck-elasticsearch-0.16.0
    app.kubernetes.io/name: eck-elasticsearch
    app.kubernetes.io/instance: es-kb-quickstart
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  version: 9.1.0
  nodeSets:
    - config:
        node.store.allow_mmap: false
      count: 1
      name: default
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 2Gi
              requests:
                memory: 2Gi
# ---
# # Source: eck-stack/charts/eck-kibana/templates/kibana.yaml
# apiVersion: kibana.k8s.elastic.co/v1
# kind: Kibana
# metadata:
#   name: es-kb-quickstart-eck-kibana
#   labels:
#     helm.sh/chart: eck-kibana-0.16.0
#     app.kubernetes.io/name: eck-kibana
#     app.kubernetes.io/instance: es-kb-quickstart
#     app.kubernetes.io/managed-by: Helm
#   annotations:
#     eck.k8s.elastic.co/license: basic
# spec:
#   version: 9.1.0
#   count: 1
#   elasticsearchRef:
#     name: elasticsearch
