---
# Source: eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  labels:
    helm.sh/chart: eck-elasticsearch-0.16.0
    app.kubernetes.io/name: eck-elasticsearch
    app.kubernetes.io/instance: es-kb-quickstart
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  version: 9.1.0
  auth:
    fileRealm:
    - secretName: secret-basic-auth
  nodeSets:
    - config:
        node.store.allow_mmap: false
      count: 1
      name: default
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 2Gi
              requests:
                memory: 2Gi
