name: kube-get-pods
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      - name: Setup Kubeconfig
        env:
          KUBECONFIG: ${{ secrets.TANUT_KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG}" > ~/.kube/config
      - run: |
          kubectl get namespace
